//! XDG Desktop Portal and GNOME application integration for River.
//!
//! GNOME apps (Settings, Files, Calculator, etc.) rely on:
//! 1. XDG Desktop Portals for file choosers, settings, screenshots
//! 2. GNOME Settings Daemon (gsd-xsettings) for GTK theme/font propagation
//! 3. A `portals.conf` that tells the portal frontend which backends to use
//! 4. D-Bus service overrides so crash recovery uses direct activation
//!    instead of failing systemd auto-activation
//!
//! This module writes the portal configuration, D-Bus overrides, GNOME app
//! environment, and ensures the River init script starts the required services.
//!
//! # Why start portals directly instead of via systemd?
//!
//! On RHEL 10.2 `xdg-desktop-portal-gtk.service` and
//! `xdg-desktop-portal-gnome.service` both have `Requisite=graphical-session.target`.
//! River does not start `graphical-session.target`, so systemd refuses to
//! activate the backend services and D-Bus auto-activation fails.
//!
//! The workaround is to start the portal binaries directly from the River init
//! script.  They register on the session D-Bus just fine; once running the
//! frontend discovers them immediately without needing systemd activation.
//!
//! To make crash recovery work, we also install D-Bus service overrides in
//! `~/.local/share/dbus-1/services/` that strip the `SystemdService=` line.
//! When a backend crashes, D-Bus falls back to direct `Exec=` activation.

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;
use tracing::info;

use crate::config::{real_user_config_dir, real_user_data_dir};
use crate::utils::{atomic_write, chown_to_real_user, run_command_logged, Manifest};

/// Portal configuration for River on RHEL 10.2.
///
/// `gnome` is tried first for interfaces it supports (Settings, Lockdown,
/// etc.), but `gtk` is explicitly mapped for dialogs because
/// `xdg-desktop-portal-gnome` does **not** provide FileChooser, AppChooser,
/// Print, or Notification on non-Mutter compositors.
///
/// `gnome-keyring` handles the Secret portal.
const PORTALS_CONF: &str = r#"# Auto-generated by sheep-rhel for River Classic
# XDG Desktop Portal backend selection

[preferred]
default=gnome;gtk;
org.freedesktop.impl.portal.FileChooser=gtk;
org.freedesktop.impl.portal.AppChooser=gtk;
org.freedesktop.impl.portal.Email=gtk;
org.freedesktop.impl.portal.Inhibit=gtk;
org.freedesktop.impl.portal.Notification=gtk;
org.freedesktop.impl.portal.Print=gtk;
org.freedesktop.impl.portal.Secret=gnome-keyring;
"#;

/// D-Bus service override that removes `SystemdService=` so D-Bus falls back
/// to direct `Exec=` activation when the backend needs to be re-activated
/// (e.g. after a crash).
const DBUS_OVERRIDE_GTK: &str = r#"[D-BUS Service]
Name=org.freedesktop.impl.portal.desktop.gtk
Exec=/usr/libexec/xdg-desktop-portal-gtk
"#;

const DBUS_OVERRIDE_GNOME: &str = r#"[D-BUS Service]
Name=org.freedesktop.impl.portal.desktop.gnome
Exec=/usr/libexec/xdg-desktop-portal-gnome
"#;

/// Environment variable configuration for GNOME apps.
///
/// `GTK_USE_PORTAL=1` forces GTK-based applications (Chrome, Waterfox,
/// LibreOffice-gtk) to use XDG Desktop Portals for file choosers instead of
/// native GTK dialogs that may lack proper Wayland support.
const GNOME_APP_ENV: &str = r#"# Auto-generated by sheep-rhel for River Classic
# GNOME application environment variables

GTK_USE_PORTAL=1
"#;

/// Write the portal configuration for River.
///
/// Without this file `xdg-desktop-portal` may pick the wrong backend
/// (or no backend) when a GNOME app requests a portal, causing silent
/// failures such as file-chooser dialogs never appearing.
pub fn configure_portals() -> Result<PathBuf> {
    let config_dir = real_user_config_dir().join("xdg-desktop-portal");
    if !crate::utils::is_dry_run() {
        fs::create_dir_all(&config_dir)
            .with_context(|| format!("Failed to create {}", config_dir.display()))?;
        chown_to_real_user(&config_dir)?;
    }

    let path = config_dir.join("portals.conf");
    atomic_write(&path, PORTALS_CONF)?;

    if !crate::utils::is_dry_run() {
        chown_to_real_user(&path)?;
    }

    info!("Wrote portal config to {}", path.display());
    Ok(path)
}

/// Write D-Bus service overrides that disable systemd activation for portal
/// backends.
///
/// The system-installed D-Bus service files contain `SystemdService=` which
/// causes D-Bus to attempt activation via systemd.  In River sessions this
/// fails because `graphical-session.target` is inactive.  These user-local
/// overrides remove the `SystemdService=` line, forcing D-Bus to use the
/// direct `Exec=` fallback instead.
///
/// Returns the paths of the written override files.
pub fn configure_dbus_overrides() -> Result<Vec<PathBuf>> {
    let services_dir = real_user_data_dir().join("dbus-1").join("services");

    if !crate::utils::is_dry_run() {
        fs::create_dir_all(&services_dir)
            .with_context(|| format!("Failed to create {}", services_dir.display()))?;
        chown_to_real_user(&services_dir)?;
    }

    let mut written = Vec::with_capacity(2);

    let gtk_path = services_dir.join("org.freedesktop.impl.portal.desktop.gtk.service");
    atomic_write(&gtk_path, DBUS_OVERRIDE_GTK)?;
    if !crate::utils::is_dry_run() {
        chown_to_real_user(&gtk_path)?;
    }
    info!("Wrote D-Bus override {}", gtk_path.display());
    written.push(gtk_path);

    let gnome_path = services_dir.join("org.freedesktop.impl.portal.desktop.gnome.service");
    atomic_write(&gnome_path, DBUS_OVERRIDE_GNOME)?;
    if !crate::utils::is_dry_run() {
        chown_to_real_user(&gnome_path)?;
    }
    info!("Wrote D-Bus override {}", gnome_path.display());
    written.push(gnome_path);

    Ok(written)
}

/// Write GNOME app environment variables.
///
/// `GTK_USE_PORTAL=1` ensures GTK-based applications use XDG Desktop Portals
/// for file choosers, print dialogs, and other desktop integration.  This is
/// critical on River because native GTK dialogs may not handle the non-GNOME
/// session correctly.
pub fn configure_gnome_app_env() -> Result<PathBuf> {
    let env_dir = real_user_config_dir().join("environment.d");
    if !crate::utils::is_dry_run() {
        fs::create_dir_all(&env_dir)
            .with_context(|| format!("Failed to create {}", env_dir.display()))?;
        chown_to_real_user(&env_dir)?;
    }

    let path = env_dir.join("90-sheep-rhel-portals.conf");
    atomic_write(&path, GNOME_APP_ENV)?;

    if !crate::utils::is_dry_run() {
        chown_to_real_user(&path)?;
    }

    info!("Wrote GNOME app environment to {}", path.display());
    Ok(path)
}

/// Stop any running portal services so the next River session starts fresh.
///
/// We stop both systemd-managed and directly-started instances, but we do
/// **not** start new ones here.  Portals are started directly by the River
/// init script (see [`gnome_services_init_snippet`]) where they can survive
/// outside of systemd's `graphical-session.target` dependency chain.
pub async fn restart_portal_services() -> Result<()> {
    if crate::utils::is_dry_run() {
        info!("[DRY-RUN] Would stop xdg-desktop-portal services");
        return Ok(());
    }

    // Stop systemd-managed instances.
    for service in [
        "xdg-desktop-portal-gtk.service",
        "xdg-desktop-portal-gnome.service",
        "xdg-desktop-portal.service",
    ] {
        let status = run_command_logged("systemctl", &["--user", "stop", service], None).await?;
        if status.success() {
            info!("Stopped {}", service);
        }
    }

    // Kill any directly-started instances that may still be running from a
    // previous River session.  We use `pgrep -f` with the full executable path
    // because process names are truncated to 15 characters in `/proc/*/stat`,
    // so `pkill -x` cannot match `xdg-desktop-portal` reliably.
    for proc in ["xdg-desktop-portal", "xdg-desktop-portal-gtk", "xdg-desktop-portal-gnome"] {
        let pattern = format!("/usr/libexec/{}", proc);
        let status = run_command_logged("pkill", &["-f", &pattern], None).await?;
        if status.success() {
            info!("Killed stray {}", proc);
        }
    }

    info!("Portal services stopped; they will be started directly by the River init script");
    Ok(())
}

/// Orchestrate the complete XDG Desktop Portal configuration.
///
/// This is the single entry-point called from `main.rs` Step 5d.
/// It writes `portals.conf`, D-Bus overrides, GNOME app environment, and
/// stops stale services so the next River session starts clean.
pub async fn apply(manifest: &mut Manifest) -> Result<()> {
    let portal_conf = configure_portals()
        .context("Failed to write portal configuration")?;
    manifest.push(crate::utils::Artifact::File {
        path: portal_conf,
    });

    let dbus_overrides = configure_dbus_overrides()
        .context("Failed to write D-Bus service overrides")?;
    for path in dbus_overrides {
        manifest.push(crate::utils::Artifact::File { path });
    }

    let env_conf = configure_gnome_app_env()
        .context("Failed to write GNOME app environment")?;
    manifest.push(crate::utils::Artifact::File {
        path: env_conf,
    });

    restart_portal_services()
        .await
        .context("Failed to restart portal services")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn portals_conf_contains_gnome_preferred() {
        assert!(PORTALS_CONF.contains("default=gnome;gtk;"));
        assert!(PORTALS_CONF.contains("gnome-keyring"));
    }

    #[test]
    fn portals_conf_maps_filechooser_to_gtk() {
        assert!(
            PORTALS_CONF.contains("org.freedesktop.impl.portal.FileChooser=gtk"),
            "FileChooser must be explicitly mapped to gtk"
        );
    }

    #[test]
    fn portals_conf_maps_dialogs_to_gtk() {
        for iface in ["AppChooser", "Email", "Inhibit", "Notification", "Print"] {
            assert!(
                PORTALS_CONF.contains(&format!("org.freedesktop.impl.portal.{}=gtk", iface)),
                "{} must be mapped to gtk",
                iface
            );
        }
    }

    #[test]
    fn dbus_override_gtk_has_no_systemd_service() {
        assert!(
            !DBUS_OVERRIDE_GTK.contains("SystemdService"),
            "GTK override must not contain SystemdService"
        );
        assert!(
            DBUS_OVERRIDE_GTK.contains("Exec=/usr/libexec/xdg-desktop-portal-gtk"),
            "GTK override must preserve correct Exec line"
        );
    }

    #[test]
    fn dbus_override_gnome_has_no_systemd_service() {
        assert!(
            !DBUS_OVERRIDE_GNOME.contains("SystemdService"),
            "GNOME override must not contain SystemdService"
        );
        assert!(
            DBUS_OVERRIDE_GNOME.contains("Exec=/usr/libexec/xdg-desktop-portal-gnome"),
            "GNOME override must preserve correct Exec line"
        );
    }

    #[test]
    fn gnome_app_env_sets_gtk_use_portal() {
        assert!(GNOME_APP_ENV.contains("GTK_USE_PORTAL=1"));
    }

    #[test]
    fn gnome_services_snippet_lists_xsettings() {
        let snippet = gnome_services_init_snippet();
        assert!(snippet.contains("gsd-xsettings"), "must start gsd-xsettings");
        assert!(snippet.contains("gsd-keyboard"), "must start gsd-keyboard");
        assert!(snippet.contains("gsd-media-keys"), "must start gsd-media-keys");
        assert!(snippet.contains("gsd-power"), "must start gsd-power");
        assert!(
            snippet.contains("xdg-desktop-portal-gtk"),
            "must start gtk portal backend directly"
        );
        assert!(
            snippet.contains("xdg-desktop-portal-gnome"),
            "must start gnome portal backend directly"
        );
        assert!(
            snippet.contains("xdg-desktop-portal"),
            "must start portal frontend"
        );
        assert!(snippet.contains("nohup"), "must use nohup to survive shell exit");
        assert!(
            snippet.contains("pgrep -u"),
            "must filter by user when cleaning up old portals"
        );
    }

    #[test]
    fn gnome_services_snippet_imports_environment() {
        let snippet = gnome_services_init_snippet();
        assert!(
            snippet.contains("systemctl --user import-environment"),
            "must import session environment into systemd"
        );
        assert!(
            snippet.contains("WAYLAND_DISPLAY"),
            "must import WAYLAND_DISPLAY"
        );
        assert!(
            snippet.contains("XDG_CURRENT_DESKTOP"),
            "must import XDG_CURRENT_DESKTOP"
        );
    }

    #[test]
    fn generated_init_contains_gnome_snippet() {
        let script = crate::theme::generate_river_init_script("rhel-red").unwrap();
        assert!(
            script.contains("gsd-xsettings"),
            "River init must start GNOME settings daemon"
        );
        assert!(
            script.contains("xdg-desktop-portal-gtk"),
            "River init must start portal gtk backend"
        );
    }

    #[test]
    fn generated_init_script_is_valid_bash() {
        let script = crate::theme::generate_river_init_script("rhel-red").unwrap();
        let output = std::process::Command::new("bash")
            .args(["-n"])
            .stdin(std::process::Stdio::piped())
            .spawn()
            .and_then(|mut child| {
                use std::io::Write;
                child.stdin.as_mut().unwrap().write_all(script.as_bytes())?;
                child.wait_with_output()
            });
        match output {
            Ok(out) if out.status.success() => {},
            Ok(out) => {
                let stderr = String::from_utf8_lossy(&out.stderr);
                panic!("Generated River init script has bash syntax errors:\n{}", stderr);
            }
            Err(e) => {
                // `bash` may not be available in the test environment; skip gracefully.
                eprintln!("Skipping bash syntax check: {}", e);
            }
        }
    }
}

/// Bash snippet that starts GNOME settings-daemon components and portal
/// backends directly inside River.
///
/// `gsd-xsettings` is the most critical: it publishes GTK theme, icon-theme,
/// font-name and text-scaling-factor over D-Bus via the XSETTINGS protocol.
/// Without it GNOME apps render with broken fonts or the wrong theme.
///
/// Portal backends are started with `nohup` so they survive after the River
/// init shell exits.  Backends are started *before* the frontend so the
/// frontend discovers them immediately instead of attempting D-Bus activation
/// through systemd (which fails because `graphical-session.target` is
/// inactive in River sessions).
pub fn gnome_services_init_snippet() -> &'static str {
    r#"
# ═══════════════════════════════════════════════════════
# GNOME application integration (XDG portals & settings)
# ═══════════════════════════════════════════════════════

# Import critical session environment into the systemd user manager.
# Without this, systemd-managed services (including the portal frontend)
# cannot access the Wayland display.
systemctl --user import-environment WAYLAND_DISPLAY DISPLAY \
    XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP \
    2>/dev/null || true

# GNOME Settings Daemon — required for correct GTK theme/font rendering.
[ -x /usr/libexec/gsd-xsettings ] && /usr/libexec/gsd-xsettings &
[ -x /usr/libexec/gsd-keyboard ]   && /usr/libexec/gsd-keyboard &
[ -x /usr/libexec/gsd-media-keys ] && /usr/libexec/gsd-media-keys &
[ -x /usr/libexec/gsd-power ]      && /usr/libexec/gsd-power &

# XDG Desktop Portal — started directly because systemd auto-activation
# fails in River sessions (backend services require graphical-session.target).
# Backends are started first so the frontend finds them on D-Bus immediately.
for p in xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-gnome; do
    for pid in $(pgrep -u "$(id -u)" -f "/usr/libexec/$p"); do
        [ "$pid" != "$$" ] && kill "$pid" 2>/dev/null
    done
done
sleep 0.5

[ -x /usr/libexec/xdg-desktop-portal-gtk ]   && nohup /usr/libexec/xdg-desktop-portal-gtk   >/dev/null 2>&1 &
[ -x /usr/libexec/xdg-desktop-portal-gnome ] && nohup /usr/libexec/xdg-desktop-portal-gnome >/dev/null 2>&1 &
sleep 1
[ -x /usr/libexec/xdg-desktop-portal ]       && nohup /usr/libexec/xdg-desktop-portal       >/dev/null 2>&1 &
"#
}
